### ISSUE TITLE
`mirror.download.kiwix.org/` is down.

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [kiwix/operations#316]
I am trying to download some content via Kiwix Android app for fixing issue https://github.com/kiwix/kiwix-android/issues/4113, but the library is not downloading in my mobile. It everytime showing failed to connect.

```kotlin
java.net.ConnectException: Failed to connect to mirror.download.kiwix.org/135.181.224.247:443
2024-12-01 12:30:47.172  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
2024-12-01 12:30:47.172  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:47.173  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2024-12-01 12:30:47.174  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:207)
2024-12-01 12:30:47.175  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
2024-12-01 12:30:47.175  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:47.175  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-12-01 12:30:47.175  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:47.175  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-12-01 12:30:47.176  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.lang.Thread.run(Thread.java:923)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  Caused by: java.net.ConnectException: failed to connect to mirror.download.kiwix.org/135.181.224.247 (port 443) from /192.168.31.23 (port 55986) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connect(IoBridge.java:134)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2024-12-01 12:30:47.183  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2024-12-01 12:30:47.184  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2024-12-01 12:30:47.184  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.Socket.connect(Socket.java:621)
2024-12-01 12:30:47.184  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2024-12-01 12:30:47.184  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2024-12-01 12:30:47.184  5606-9008  System.err              org.kiwix.kiwixmobile                W  	... 29 more
2024-12-01 12:30:47.185  5606-9008  System.err              org.kiwix.kiwixmobile                W  Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:47.185  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
2024-12-01 12:30:47.185  5606-9008  System.err              org.kiwix.kiwixmobile                W  	... 39 more
2024-12-01 12:30:50.119  5606-6439  wix.kiwixmobil          org.kiwix.kiwixmobile                I  Explicit concurrent copying GC freed 64689(5052KB) AllocSpace objects, 10(2392KB) LOS objects, 55% free, 9665KB/21MB, paused 339us total 158.034ms
2024-12-01 12:30:50.182  5606-8944  System.err              org.kiwix.kiwixmobile                W  java.net.ConnectException: Failed to connect to mirror.download.kiwix.org/135.181.224.247:443
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-12-01 12:30:50.183  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:207)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:50.184  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-12-01 12:30:50.185  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.lang.Thread.run(Thread.java:923)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  Caused by: java.net.ConnectException: failed to connect to mirror.download.kiwix.org/135.181.224.247 (port 443) from /192.168.31.23 (port 56000) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connect(IoBridge.java:134)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2024-12-01 12:30:50.186  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at java.net.Socket.connect(Socket.java:621)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2024-12-01 12:30:50.187  5606-8944  System.err              org.kiwix.kiwixmobile                W  	... 29 more
2024-12-01 12:30:50.188  5606-8944  System.err              org.kiwix.kiwixmobile                W  Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:50.188  5606-8944  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
2024-12-01 12:30:50.188  5606-8944  System.err              org.kiwix.kiwixmobile                W  	... 39 more
2024-12-01 12:30:53.492  5606-9008  System.err              org.kiwix.kiwixmobile                W  java.net.ConnectException: Failed to connect to mirror.download.kiwix.org/135.181.224.247:443
2024-12-01 12:30:53.493  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
2024-12-01 12:30:53.493  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
2024-12-01 12:30:53.494  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
2024-12-01 12:30:53.495  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.OkHttpCall.execute(OkHttpCall.java:207)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:53.496  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Observable.subscribe(Observable.java:12284)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
2024-12-01 12:30:53.497  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2024-12-01 12:30:53.498  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
2024-12-01 12:30:53.498  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2024-12-01 12:30:53.498  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2024-12-01 12:30:53.498  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.lang.Thread.run(Thread.java:923)
2024-12-01 12:30:53.499  5606-9008  System.err              org.kiwix.kiwixmobile                W  Caused by: java.net.ConnectException: failed to connect to mirror.download.kiwix.org/135.181.224.247 (port 443) from /192.168.31.23 (port 56012) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:53.500  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:287)
2024-12-01 12:30:53.500  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connectErrno(IoBridge.java:192)
2024-12-01 12:30:53.500  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.connect(IoBridge.java:134)
2024-12-01 12:30:53.500  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
2024-12-01 12:30:53.501  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
2024-12-01 12:30:53.501  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
2024-12-01 12:30:53.501  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
2024-12-01 12:30:53.501  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
2024-12-01 12:30:53.502  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at java.net.Socket.connect(Socket.java:621)
2024-12-01 12:30:53.502  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
2024-12-01 12:30:53.502  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
2024-12-01 12:30:53.502  5606-9008  System.err              org.kiwix.kiwixmobile                W  	... 29 more
2024-12-01 12:30:53.503  5606-9008  System.err              org.kiwix.kiwixmobile                W  Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
2024-12-01 12:30:53.504  5606-9008  System.err              org.kiwix.kiwixmobile                W  	at libcore.io.IoBridge.isConnected(IoBridge.java:274)
2024-12-01 12:30:53.504  5606-9008  System.err              org.kiwix.kiwixmobile                W  	... 39 more
```

The site is also not opening in my browser.

![Image](https://github.com/user-attachments/assets/93d996a2-b9db-45c7-b4d5-bc82afdd181c)

As well as https://download.kiwix.org/ is also not opening in my browser

![Image](https://github.com/user-attachments/assets/7877c4aa-cbe7-431b-b3d8-701e61bfc5f3)

Is it somehow related to https://github.com/kiwix/operations/issues/289?

**Comment by MohitMaliFtechiz** [comment]
@rgaudin Can you please have a look at this?

**Comment by rgaudin** [comment]
@MohitMaliFtechiz this is a known issue ; we're working with our hosting provider to get it back.

**Comment by benoit74** [comment]
For those who missed the info, all updates on this major issue are posted at https://mastodon.social/@kiwix/

**Comment by kelson42** [comment]
I guess we can close that issue!?
